### PR TITLE
libspatialite: add package and dependencies

### PR DESCRIPTION
**Pull request by Grimler91**

### CODE REVIEW

**Comment by Grimler91** [comment]
Closes https://github.com/termux/science-packages/issues/58

**Comment by dead10ck** [comment]
Thanks so much for the quick turnaround! I just got around to testing this. Strangely, it looks like `ogrinfo` got compiled with spatialite support, but not gdal the library itself, nor `ogr2ogr`.

```
❯ ogr2ogr -f sqlite -dsco 'SPATIALITE=YES' roads.sqlite fixtures/roads.geojson
Warning 6: driver SQLite does not support creation option SPATIALITE
ERROR 6: OGR was built without libspatialite support
... sorry, creating/writing any SpatiaLite DB is unsupported

ERROR 1: sqlite driver failed to create roads.sqlite

❯ ogrinfo -dialect sqlite -sql "select sqlite_version();" fixtures/roads.geojson
INFO: Open of `fixtures/roads.geojson'
using driver `GeoJSON' successful.                                                                                            Layer name: SELECT                                                Geometry: None
Feature Count: 1
Layer SRS WKT:
(unknown)
sqlite_version(): String (0.0)
OGRFeature(SELECT):0
  sqlite_version() (String) = 3.34.0
```

**Comment by Grimler91** [comment]
Thanks for testing, I missed to check in a line. Hopefully works better in [3.2.1-2](https://github.com/termux/science-packages/commit/cd6addece9da2e863d492ea806cd72cb8aa76bf3)!

**Comment by dead10ck** [comment]
Awesome, thanks, will test when it's out!

**Comment by dead10ck** [comment]
Just tested, and the two commands I pasted above are working now! Thanks so much!!

**Pull request merged**
