### PR TITLE
gdal: add libexpat as dependency in order to read gpx and kml files

### PR DESCRIPTION
**Pull request by danobr**
As described in https://gdal.org/drivers/vector/gpx.html :

> OGR has support for GPX reading (if GDAL is build with expat library support) and writing.

Also in https://gdal.org/drivers/vector/kml.html :

> KML reading is only available if GDAL/OGR is built with the Expat XML Parser, otherwise only KML writing will be supported.

I am therefore adding libexpat as a dependency.

TODO
- [ ] Manual test

### CODE REVIEW

**Comment by Grimler91** [comment]
Hi, thanks, 
Looks like it's failing with 
```sh
/bin/bash /home/builder/.termux-build/gdal/src/libtool --mode=compile --silent --tag=CC aarch64-linux-android-clang -I/home/builder/.termux-build/gdal/src/port -I/home/builder/.termux-build/gdal/src/gcore -I/home/builder/.termux-build/gdal/src/alg -I/home/builder/.termux-build/gdal/src/ogr -I/home/builder/.termux-build/gdal/src/ogr/ogrsf_frmts -I/home/builder/.termux-build/gdal/src/gnm -I/home/builder/.termux-build/gdal/src/apps -fstack-protector-strong -Oz  -Wall -Wdeclaration-after-statement -Wextra -Winit-self -Wunused-parameter -Wmissing-prototypes -Wmissing-declarations -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdeclaration-after-statement -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync  -I../frmts/vrt -DINTERNAL_QHULL -DHAVE_GEOS=1 -I/data/data/com.termux/files/usr/include -DGNM_ENABLED -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/gdal/src/port -I/data/data/com.termux/files/usr/include/openjpeg-2.3  -DGDAL_COMPILATION    -Imarching_squares -c -o delaunay.lo delaunay.c
In file included from ogr2kmlgeometry.cpp:30:
In file included from /home/builder/.termux-build/gdal/src/port/cpl_port.h:612:
/home/builder/.termux-build/_cache/android-r20-api-24-v1/bin/../sysroot/usr/include/c++/v1/cmath:314:9: error: no member named 'signbit' in the global namespace; did you mean '__signbit'?
using ::signbit;
      ~~^
/usr/include/bits/mathcalls-helper-functions.h:25:20: note: '__signbit' declared here
__MATHDECL_1 (int, __signbit,, (_Mdouble_ __value))
                   ^
In file included from ogr2kmlgeometry.cpp:30:
In file included from /home/builder/.termux-build/gdal/src/port/cpl_port.h:612:
/home/builder/.termux-build/_cache/android-r20-api-24-v1/bin/../sysroot/usr/include/c++/v1/cmath:315:9: error: no member named 'fpclassify' in the global namespace; did you mean '__fpclassify'?
using ::fpclassify;
      ~~^
/usr/include/bits/mathcalls-helper-functions.h:21:20: note: '__fpclassify' declared here
__MATHDECL_1 (int, __fpclassify,, (_Mdouble_ __value))
                   ^
In file included from ogr2kmlgeometry.cpp:30:
In file included from /home/builder/.termux-build/gdal/src/port/cpl_port.h:612:
/home/builder/.termux-build/_cache/android-r20-api-24-v1/bin/../sysroot/usr/include/c++/v1/cmath:316:9: error: no member named 'isfinite' in the global namespace
using ::isfinite;
      ~~^
/home/builder/.termux-build/_cache/android-r20-api-24-v1/bin/../sysroot/usr/include/c++/v1/cmath:317:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/home/builder/.termux-build/_cache/android-r20-api-24-v1/bin/../sysroot/usr/include/c++/v1/cmath:318:9: error: no member named 'isnan' in the global namespace
using ::isnan;
[...]
```

Which I've seen before (related to https://github.com/termux/termux-packages/issues/1149 (?)). Just need to figure how we solved it again

**Comment by Grimler91** [comment]
Feels like I've even fixed this before for gdal even..

**Comment by danobr** [comment]
Thanks a lot @Grimler91 for your help with this PR. Really appreciate it! :)

I'm kinda blocked debugging because I am traveling for several months and I don't have access to a proper PC (only Android devices). I love Termux, but I find it hard to do actual dev work with it. The truth is that I was expecting this to be an easy PR for adding a small feature I needed. 

Should I keep the PR open or would you like me to transform this into an issue? I am definitely interested in investigating this, and eventually contributing more to Termux, but it won't be for now.

**Comment by Grimler91** [comment]
Just an update: compiling with libexpat support on device works fine so just need to fix the compilation error when cross-compiling

**Comment by thunder-coding** [comment]
Any update on this?

**Pull request closed without merging**
